meta:
  use_bfloat16: true
  model_name: "vit_base"
  copy_data: false
  pred_depth: 4
  pred_emb_dim: 384
  load_checkpoint: false
  read_checkpoint: null
mask:
  patch_size: 16
  allow_overlap: false
  min_keep: 4
  mask_scale: [0.1, 0.25]
data:
  root_path: "/kaggle/working"
  batch_size: 32
  num_workers: 2
  pin_mem: true
  crop_size: 128
  image_folder: ""
  use_gaussian_blur: false
  color_jitter_strength: 0.0
  crop_scale:
    - 0.3
    - 0.1
  use_horizontal_flip: false
  use_color_distortion: false
optimization:
  epochs: 50
  warmup_epochs: 5
  lr: 0.001
  min_lr: 0.00001
  weight_decay: 0.05
